/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAgendaRouteImport } from './routes/_shell.agenda'
import { Route as ShellAssinaturasRouteImport } from './routes/_shell.assinaturas'
import { Route as ShellAuditoriaRouteImport } from './routes/_shell.auditoria'
import { Route as ShellAvaliacoesRouteImport } from './routes/_shell.avaliacoes'
import { Route as ShellComunicacaoRouteImport } from './routes/_shell.comunicacao'
import { Route as ShellConfiguracoesRouteImport } from './routes/_shell.configuracoes'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDocumentosRouteImport } from './routes/_shell.documentos'
import { Route as ShellEvolucoesRouteImport } from './routes/_shell.evolucoes'
import { Route as ShellFinanceiroRouteImport } from './routes/_shell.financeiro'
import { Route as ShellPlanosRouteImport } from './routes/_shell.planos'
import { Route as ShellProntuariosRouteImport } from './routes/_shell.prontuarios'
import { Route as ShellRelatoriosRouteImport } from './routes/_shell.relatorios'
import { Route as ShellPacientesIndexRouteImport } from './routes/_shell.pacientes.index'
import { Route as ShellPacientesIdRouteImport } from './routes/_shell.pacientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAgendaRoute = ShellAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssinaturasRoute = ShellAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditoriaRoute = ShellAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAvaliacoesRoute = ShellAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComunicacaoRoute = ShellComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfiguracoesRoute = ShellConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentosRoute = ShellDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEvolucoesRoute = ShellEvolucoesRouteImport.update({
  id: '/evolucoes',
  path: '/evolucoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFinanceiroRoute = ShellFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlanosRoute = ShellPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProntuariosRoute = ShellProntuariosRouteImport.update({
  id: '/prontuarios',
  path: '/prontuarios',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRelatoriosRoute = ShellRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPacientesIndexRoute = ShellPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPacientesIdRoute = ShellPacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof ShellAgendaRoute
  '/assinaturas': typeof ShellAssinaturasRoute
  '/auditoria': typeof ShellAuditoriaRoute
  '/avaliacoes': typeof ShellAvaliacoesRoute
  '/comunicacao': typeof ShellComunicacaoRoute
  '/configuracoes': typeof ShellConfiguracoesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documentos': typeof ShellDocumentosRoute
  '/evolucoes': typeof ShellEvolucoesRoute
  '/financeiro': typeof ShellFinanceiroRoute
  '/planos': typeof ShellPlanosRoute
  '/prontuarios': typeof ShellProntuariosRoute
  '/relatorios': typeof ShellRelatoriosRoute
  '/pacientes/$id': typeof ShellPacientesIdRoute
  '/pacientes/': typeof ShellPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof ShellAgendaRoute
  '/assinaturas': typeof ShellAssinaturasRoute
  '/auditoria': typeof ShellAuditoriaRoute
  '/avaliacoes': typeof ShellAvaliacoesRoute
  '/comunicacao': typeof ShellComunicacaoRoute
  '/configuracoes': typeof ShellConfiguracoesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documentos': typeof ShellDocumentosRoute
  '/evolucoes': typeof ShellEvolucoesRoute
  '/financeiro': typeof ShellFinanceiroRoute
  '/planos': typeof ShellPlanosRoute
  '/prontuarios': typeof ShellProntuariosRoute
  '/relatorios': typeof ShellRelatoriosRoute
  '/pacientes/$id': typeof ShellPacientesIdRoute
  '/pacientes': typeof ShellPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/agenda': typeof ShellAgendaRoute
  '/_shell/assinaturas': typeof ShellAssinaturasRoute
  '/_shell/auditoria': typeof ShellAuditoriaRoute
  '/_shell/avaliacoes': typeof ShellAvaliacoesRoute
  '/_shell/comunicacao': typeof ShellComunicacaoRoute
  '/_shell/configuracoes': typeof ShellConfiguracoesRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/documentos': typeof ShellDocumentosRoute
  '/_shell/evolucoes': typeof ShellEvolucoesRoute
  '/_shell/financeiro': typeof ShellFinanceiroRoute
  '/_shell/planos': typeof ShellPlanosRoute
  '/_shell/prontuarios': typeof ShellProntuariosRoute
  '/_shell/relatorios': typeof ShellRelatoriosRoute
  '/_shell/pacientes/$id': typeof ShellPacientesIdRoute
  '/_shell/pacientes/': typeof ShellPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/assinaturas'
    | '/auditoria'
    | '/avaliacoes'
    | '/comunicacao'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/evolucoes'
    | '/financeiro'
    | '/planos'
    | '/prontuarios'
    | '/relatorios'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/assinaturas'
    | '/auditoria'
    | '/avaliacoes'
    | '/comunicacao'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/evolucoes'
    | '/financeiro'
    | '/planos'
    | '/prontuarios'
    | '/relatorios'
    | '/pacientes/$id'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/agenda'
    | '/_shell/assinaturas'
    | '/_shell/auditoria'
    | '/_shell/avaliacoes'
    | '/_shell/comunicacao'
    | '/_shell/configuracoes'
    | '/_shell/dashboard'
    | '/_shell/documentos'
    | '/_shell/evolucoes'
    | '/_shell/financeiro'
    | '/_shell/planos'
    | '/_shell/prontuarios'
    | '/_shell/relatorios'
    | '/_shell/pacientes/$id'
    | '/_shell/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/agenda': {
      id: '/_shell/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof ShellAgendaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assinaturas': {
      id: '/_shell/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof ShellAssinaturasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/auditoria': {
      id: '/_shell/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof ShellAuditoriaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/avaliacoes': {
      id: '/_shell/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof ShellAvaliacoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/comunicacao': {
      id: '/_shell/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof ShellComunicacaoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/configuracoes': {
      id: '/_shell/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ShellConfiguracoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documentos': {
      id: '/_shell/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof ShellDocumentosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/evolucoes': {
      id: '/_shell/evolucoes'
      path: '/evolucoes'
      fullPath: '/evolucoes'
      preLoaderRoute: typeof ShellEvolucoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/financeiro': {
      id: '/_shell/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof ShellFinanceiroRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/planos': {
      id: '/_shell/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof ShellPlanosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/prontuarios': {
      id: '/_shell/prontuarios'
      path: '/prontuarios'
      fullPath: '/prontuarios'
      preLoaderRoute: typeof ShellProntuariosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/relatorios': {
      id: '/_shell/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof ShellRelatoriosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pacientes/': {
      id: '/_shell/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof ShellPacientesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pacientes/$id': {
      id: '/_shell/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof ShellPacientesIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAgendaRoute: typeof ShellAgendaRoute
  ShellAssinaturasRoute: typeof ShellAssinaturasRoute
  ShellAuditoriaRoute: typeof ShellAuditoriaRoute
  ShellAvaliacoesRoute: typeof ShellAvaliacoesRoute
  ShellComunicacaoRoute: typeof ShellComunicacaoRoute
  ShellConfiguracoesRoute: typeof ShellConfiguracoesRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDocumentosRoute: typeof ShellDocumentosRoute
  ShellEvolucoesRoute: typeof ShellEvolucoesRoute
  ShellFinanceiroRoute: typeof ShellFinanceiroRoute
  ShellPlanosRoute: typeof ShellPlanosRoute
  ShellProntuariosRoute: typeof ShellProntuariosRoute
  ShellRelatoriosRoute: typeof ShellRelatoriosRoute
  ShellPacientesIdRoute: typeof ShellPacientesIdRoute
  ShellPacientesIndexRoute: typeof ShellPacientesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAgendaRoute: ShellAgendaRoute,
  ShellAssinaturasRoute: ShellAssinaturasRoute,
  ShellAuditoriaRoute: ShellAuditoriaRoute,
  ShellAvaliacoesRoute: ShellAvaliacoesRoute,
  ShellComunicacaoRoute: ShellComunicacaoRoute,
  ShellConfiguracoesRoute: ShellConfiguracoesRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDocumentosRoute: ShellDocumentosRoute,
  ShellEvolucoesRoute: ShellEvolucoesRoute,
  ShellFinanceiroRoute: ShellFinanceiroRoute,
  ShellPlanosRoute: ShellPlanosRoute,
  ShellProntuariosRoute: ShellProntuariosRoute,
  ShellRelatoriosRoute: ShellRelatoriosRoute,
  ShellPacientesIdRoute: ShellPacientesIdRoute,
  ShellPacientesIndexRoute: ShellPacientesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
